export const PREDEFINED_REAL_ESTATE_QA = [
  { question: "What is required for the rental application process?", answer: "Applicants must provide a valid state ID, their last 3 months of pay stubs, bank statements, and submit to a credit and background check." },
  { question: "How much is the standard security deposit?", answer: "The standard security deposit is equivalent to one month's rent, payable in full upon signing the lease agreement." },
  { question: "Are pets allowed in the rental properties?", answer: "Pet policies vary by property. Some allow small dogs or cats with a monthly pet fee or additional deposit, while others are pet-free." },
  { question: "Is renter's insurance mandatory?", answer: "Yes, all tenants are required to maintain a renter's insurance policy with a minimum of $100,000 in liability coverage." },
  { question: "What utility costs are included in the monthly rent?", answer: "Water and trash collection are generally included. Electricity, gas, internet, and cable are the tenant's responsibility unless specified." },
  { question: "How do I request maintenance services?", answer: "Maintenance requests can be submitted online through the tenant portal or by calling our support line for emergencies." },
  { question: "Can I make cosmetic changes or paint the walls?", answer: "Any cosmetic changes or painting require prior written authorization from the property manager or landlord." },
  { question: "What happens if I need to break my lease early?", answer: "Early termination requires a 60-day written notice and a termination fee equivalent to two months' rent." },
  { question: "How is the monthly rent paid?", answer: "Rent is paid online via direct ACH transfer, credit card, or check by the 1st of each calendar month." },
  { question: "Is there a grace period for late rent payments?", answer: "Rent is late after the 5th of the month, at which point a standard 10% late fee is automatically applied." },
  { question: "What is a mortgage pre-approval?", answer: "A mortgage pre-approval is a lender's commitment to lend you a specific amount based on your credit score, income, and assets." },
  { question: "What are typical buyer closing costs?", answer: "Closing costs range between 2% to 5% of the purchase price, covering loan origination, titles, escrow fees, and taxes." },
  { question: "Do I need a home inspection before buying?", answer: "Yes, we strongly recommend a professional home inspection to identify any underlying structural or systemic issues before closing." },
  { question: "What is an escrow account?", answer: "An escrow account is a neutral holding account where funds (like earnest money deposits) are kept secure during the transaction." },
  { question: "How long does the home buying process usually take?", answer: "From offer acceptance to closing keys, the average transaction takes between 30 to 45 calendar days." },
  { question: "What is earnest money?", answer: "Earnest money is a good faith deposit (usually 1% to 3% of the price) submitted shortly after an offer is accepted." },
  { question: "Who pays the real estate agent commission?", answer: "Typically, the property seller pays the commissions for both the listing agent and the buyer's agent at closing." },
  { question: "What is a seller's disclosure statement?", answer: "A seller's disclosure is a document where the seller lists known issues, repairs, or defects regarding the property's condition." },
  { question: "How do I make an offer on a property?", answer: "Your real estate agent will draft a formal purchase contract outlining your price, terms, contingencies, and closing timeline." },
  { question: "What does under contract mean?", answer: "Under contract means the buyer and seller have signed a binding agreement, but have not yet completed all closing contingencies." },
  { question: "What is property appraisal?", answer: "An appraisal is an independent valuation of the property's market worth conducted by a licensed appraiser for the lender." },
  { question: "How much down payment do I need?", answer: "Down payments vary from 3% for conventional loans up to 20% to avoid paying private mortgage insurance (PMI)." },
  { question: "What is a property viewing consultation?", answer: "A consultation is a private meeting at the property listing where an agent walks you through details and answers questions." },
  { question: "Is there a booking fee for property viewings?", answer: "Yes, we charge a $50 viewing deposit fee to filter serious prospects, which can be paid online or in cash on-site." },
  { question: "Can I reschedule my viewing appointment?", answer: "Yes, you can reschedule your viewing appointment up to 24 hours prior to the slot directly from your client portal." },
  { question: "Can I cancel my viewing appointment for a refund?", answer: "Cancellations made 24 hours in advance will receive a full refund of the $50 viewing fee deposit." },
  { question: "What happens if I do not show up for my viewing?", answer: "No-shows without prior cancellation notice forfeit their $50 deposit fee." },
  { question: "Are home viewings available on weekends?", answer: "Weekend viewing availability is subject to the individual agency's operating hours defined in settings." },
  { question: "Do you offer virtual video walk-throughs?", answer: "Yes, our voice assistant or support agents can coordinate live video walk-through tours upon request." },
  { question: "What is the difference between pending and active listings?", answer: "Active listings are fully available, while pending listings are under contract with buyers completing final contingencies." }
]
