export const PREDEFINED_REAL_ESTATE_QA = [
  // Indian Real Estate Market Q&As
  { question: "Is this property RERA registered?", answer: "Yes, all our active listings are fully registered under the State Real Estate Regulatory Authority (RERA) with valid registration certificates available for verification." },
  { question: "What are the stamp duty and registration charges in India?", answer: "Stamp duty typically ranges from 4% to 8% of the property value depending on the state, with an additional 1% registration fee." },
  { question: "Is the property Vaastu compliant?", answer: "We have a dedicated filter for Vaastu compliance. Many listings feature East-facing entrances, kitchens in the Agni (South-East) corner, and master bedrooms in the South-West." },
  { question: "What is the difference between carpet area and super built-up area?", answer: "Car carpet area is the net usable floor area inside the walls. Super built-up area includes common areas like corridors, lifts, and lobby space (usually 30-40% loading)." },
  { question: "What utilities and amenities are covered under society maintenance?", answer: "Society maintenance typically covers 24/7 security, power backup, elevator operations, swimming pool/gym access, and water charges." },
  { question: "Does the project have a Occupancy Certificate (OC)?", answer: "Yes, completed properties have valid Occupancy Certificates issued by the local municipal corporation, ensuring it is safe for possession." },
  { question: "Are home loans available from major public banks (SBI, HDFC)?", answer: "Yes, our properties are pre-approved for home loans by major Indian financial institutions including SBI, HDFC, ICICI, and LIC Housing Finance." },
  { question: "What is the standard booking amount (earnest money) in India?", answer: "The standard token or booking amount is typically 2% to 10% of the agreement value, paid to initiate the sale agreement." },
  { question: "Is power backup available for air conditioners?", answer: "Most high-end apartment complexes feature 100% DG (Diesel Generator) power backup that supports heavy appliances including ACs and geysers." },
  { question: "What is the difference between freehold and leasehold property?", answer: "Freehold properties grant complete ownership of the land and building indefinitely, whereas leasehold land is owned by local authorities (e.g., HUDA, DDA) for a term of 99 years." },
  
  // General Q&As
  { question: "What is required for the rental application process?", answer: "Applicants must provide a valid Aadhaar card, PAN card, last 3 months salary slips, and submit a signed tenant police verification form." },
  { question: "How much is the standard security deposit?", answer: "The standard security deposit is equivalent to one month's rent, payable in full upon signing the lease agreement." },
  { question: "Are pets allowed in the rental properties?", answer: "Pet policies vary by property. Some allow small dogs or cats with a monthly pet fee or additional deposit, while others are pet-free." },
  { question: "Is renter's insurance mandatory?", answer: "Yes, all tenants are required to maintain a renter's insurance policy with a minimum of $100,000 in liability coverage." },
  { question: "How is the monthly rent paid?", answer: "Rent is paid online via direct ACH transfer, credit card, or check by the 1st of each calendar month." },
  { question: "Is there a grace period for late rent payments?", answer: "Rent is late after the 5th of the month, at which point a standard 10% late fee is automatically applied." },
  { question: "What is earnest money?", answer: "Earnest money is a good faith deposit (usually 1% to 3% of the price) submitted shortly after an offer is accepted." },
  { question: "Who pays the real estate agent commission?", answer: "Typically, the property seller pays the commissions for both the listing agent and the buyer's agent at closing." },
  { question: "What is a seller's disclosure statement?", answer: "A seller's disclosure is a document where the seller lists known issues, repairs, or defects regarding the property's condition." },
  { question: "How do I make an offer on a property?", answer: "Your real estate agent will draft a formal purchase contract outlining your price, terms, contingencies, and closing timeline." },
  { question: "What does under contract mean?", answer: "Under contract means the buyer and seller have signed a binding agreement, but have not yet completed all closing contingencies." },
  { question: "What is property appraisal?", answer: "An appraisal is an independent valuation of the property's market worth conducted by a licensed appraiser for the lender." },
  { question: "How much down payment do I need?", answer: "Down payments vary from 3% for conventional loans up to 20% to avoid paying private mortgage insurance (PMI)." },
  { question: "What is a property viewing consultation?", answer: "A consultation is a private meeting at the property listing where an agent walks you through details and answers questions." },
  { question: "Is there a booking fee for property viewings?", answer: "Yes, we charge a Rs 500 viewing deposit fee to filter serious prospects, which can be paid online or in cash on-site." },
  { question: "Can I reschedule my viewing appointment?", answer: "Yes, you can reschedule your viewing appointment up to 24 hours prior to the slot directly from your client portal." },
  { question: "Can I cancel my viewing appointment for a refund?", answer: "Cancellations made 24 hours in advance will receive a full refund of the viewing fee deposit." },
  { question: "What happens if I do not show up for my viewing?", answer: "No-shows without prior cancellation notice forfeit their deposit fee." },
  { question: "Are viewings available on weekends?", answer: "Weekend viewing availability is subject to the individual agency's operating hours defined in settings." },
  { question: "Do you offer virtual video walk-throughs?", answer: "Yes, our voice assistant or support agents can coordinate live video walk-through tours upon request." }
]
